[package]
name = "concatter"
version = "0.1.0"
authors = ["Anton Gustafsson <antonnorengustafsson@gmail.com>"]
edition = "2018"

[dependencies]
tiny_http = "0.6.2"
reqwest = "0.9.16"
serde = "1.0.91"
serde_json = "1.0.39"
rayon = "1.0.3"
chashmap = "2.2.2"
clap = "2.33.0"